[[IgnoredVulns]]
id = "GO-2022-0968"
# ignore_until = 2022-11-09T00:00:00Z # Optional exception expiry date
reason = "No ssh servers are connected to or hosted in Go lang"

[[IgnoredVulns]]
id = "GO-2022-1059"
# ignore_until = 2022-11-09T00:00:00Z # Optional exception expiry date
reason = "No external http servers are written in Go lang."

[[IgnoredVulns]]
id = "GO-2022-0356"
# ignore_until = 2022-11-09T00:00:00Z # Optional exception expiry date
reason = "No ssh servers"

[[IgnoredVulns]]
id = "GO-2022-0969"
# ignore_until = 2022-11-09T00:00:00Z # Optional exception expiry date
reason = "No external http servers in Go lang."
