name: Scheduled link check

on: 
  schedule:
    - cron: '30 22 * * 1,4'
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@25b2c436c653f0d4500d3c2df86e5c14e71e44e1
      with:
        use-quiet-mode: "yes"
        
# Documentation available here: https://github.com/marketplace/actions/markdown-link-check
